<a href="https://colab.research.google.com/github/GundadiAravind/machine-learning/blob/main/ml_style_of_finding_weights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
age = [20, 30, 25, 40, 27, 28, 22, 24, 31]
len(age)

9

In [ ]:
exp = [0, 5, 2, 10, 4, 3.5, 1, 2, 6]
len(exp)

9

In [ ]:
age = np.array(age)
exp = np.array(exp)
income = age * 2 + exp * 3 + 5
income

array([ 45. ,  80. ,  61. , 115. ,  71. ,  71.5,  52. ,  59. ,  85. ])

In [ ]:
np.c_[age, exp, income]

array([[ 20. ,   0. ,  45. ],
       [ 30. ,   5. ,  80. ],
       [ 25. ,   2. ,  61. ],
       [ 40. ,  10. , 115. ],
       [ 27. ,   4. ,  71. ],
       [ 28. ,   3.5,  71.5],
       [ 22. ,   1. ,  52. ],
       [ 24. ,   2. ,  59. ],
       [ 31. ,   6. ,  85. ]])

In [ ]:
ones = np.ones(len(age))
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# step1 : feature matrix
X = np.c_[ones, age, exp]
X

array([[ 1. , 20. ,  0. ],
       [ 1. , 30. ,  5. ],
       [ 1. , 25. ,  2. ],
       [ 1. , 40. , 10. ],
       [ 1. , 27. ,  4. ],
       [ 1. , 28. ,  3.5],
       [ 1. , 22. ,  1. ],
       [ 1. , 24. ,  2. ],
       [ 1. , 31. ,  6. ]])

In [ ]:
# step2 : label(target) matrx
Y = np.c_[income]
Y


array([[ 45. ],
       [ 80. ],
       [ 61. ],
       [115. ],
       [ 71. ],
       [ 71.5],
       [ 52. ],
       [ 59. ],
       [ 85. ]])

In [ ]:
# step3 : random weights.
W = np.random.random((3, 1))
W

array([[0.7971683 ],
       [0.45533802],
       [0.60509197]])

In [ ]:
# trial 1.
# prediction
ycap = X.dot(W)
# loss
mse = ((Y-ycap)**2).mean()
# derivative
delta = X.T.dot(Y-ycap)/len(age)

# adjust
W += delta * 0.02
print("Current Loss ", mse)
print(" Latert Weights " , W)

Current Loss  3319.717859620023
 Latert Weights  [[ 1.90736032]
 [32.64480613]
 [ 5.61846174]]


In [ ]:
# trial 2.
# prediction
ycap = X.dot(W)
# loss
mse = ((Y-ycap)**2).mean()
# derivative
delta = X.T.dot(Y-ycap)/len(age)

# adjust
W += delta * 0.02
print("Current Loss ", mse)
print(" Latert Weights " , W)

Current Loss  750406.1603137616
 Latert Weights  [[ -15.0463104 ]
 [-452.55210686]
 [ -67.62662875]]


In [ ]:
np.std(age)

np.float64(5.579946457550986)

In [ ]:
np.std(exp)

np.float64(2.8588178511708016)

In [ ]:
np.std(income)

np.float64(19.703982175698567)

In [ ]:

def scale(c):
  return    (c-c.mean())/c.std()

In [ ]:
scale(age)

array([-1.33414263,  0.45798926, -0.43807668,  2.25012115, -0.07965031,
        0.09956288, -0.97571625, -0.61728987,  0.63720245])

In [ ]:
scale(age).std()

np.float64(1.0)

In [ ]:
scale(exp)


array([-1.30201447,  0.44696019, -0.60242461,  2.19593486,  0.09716526,
       -0.07773221, -0.95221954, -0.60242461,  0.79675513])

In [ ]:
scale(exp).std()

np.float64(1.0000000000000002)

In [ ]:
scale(income)

array([-1.32234973,  0.45394095, -0.51033113,  2.23023164, -0.00281951,
        0.02255607, -0.9670916 , -0.61183346,  0.70769677])

In [ ]:
scale(income).std()

np.float64(1.0)

In [ ]:
X

array([[ 1. , 20. ,  0. ],
       [ 1. , 30. ,  5. ],
       [ 1. , 25. ,  2. ],
       [ 1. , 40. , 10. ],
       [ 1. , 27. ,  4. ],
       [ 1. , 28. ,  3.5],
       [ 1. , 22. ,  1. ],
       [ 1. , 24. ,  2. ],
       [ 1. , 31. ,  6. ]])

In [ ]:
X_original = X.copy()

In [ ]:
for i in range(X.shape[1]):
   if i != 0:
     X[:, i]= scale(X[:, i])

In [ ]:
X

array([[ 1.        , -1.33414263, -1.30201447],
       [ 1.        ,  0.45798926,  0.44696019],
       [ 1.        , -0.43807668, -0.60242461],
       [ 1.        ,  2.25012115,  2.19593486],
       [ 1.        , -0.07965031,  0.09716526],
       [ 1.        ,  0.09956288, -0.07773221],
       [ 1.        , -0.97571625, -0.95221954],
       [ 1.        , -0.61728987, -0.60242461],
       [ 1.        ,  0.63720245,  0.79675513]])

In [ ]:
X[:, 1].std()

np.float64(1.0)

In [ ]:
X[:, 2].std()

np.float64(1.0000000000000002)

In [ ]:
Y_original = Y.copy()

In [ ]:
Y = scale(Y)
Y

array([[-1.32234973],
       [ 0.45394095],
       [-0.51033113],
       [ 2.23023164],
       [-0.00281951],
       [ 0.02255607],
       [-0.9670916 ],
       [-0.61183346],
       [ 0.70769677]])

In [ ]:
Y.std()

np.float64(1.0)

In [ ]:
# random weights.
np.random.seed(101)
W = np.random.random((3, 1)) * 2 - 1
W

array([[ 0.03279726],
       [ 0.14133517],
       [-0.94305155]])

In [ ]:
# trial 1.
ycap = X.dot(W)
loss = ((Y-ycap)**2).mean()
delta = X.T.dot(Y-ycap)/Y.size
W += delta *0.02
print(" current Loss ", loss)

 current Loss  3.2453659375004267


In [ ]:
# trial 2.
ycap = X.dot(W)
loss = ((Y-ycap)**2).mean()
delta = X.T.dot(Y-ycap)/Y.size
W += delta *0.02
print(" current Loss ", loss)

 current Loss  2.9920377238515714


In [ ]:
# trial 1.
ycap = X.dot(W)
loss = ((Y-ycap)**2).mean()
delta = X.T.dot(Y-ycap)/Y.size
W += delta *0.02
print(" current Loss ", loss)

 current Loss  2.7585038659152286


In [ ]:
W

array([[ 0.03086851],
       [ 0.24474316],
       [-0.83926221]])